services:
  # データベース
  mysql:
    image: mysql:8.0
    container_name: common-mysql
    networks:
      - common-net
    restart: always
    environment:
      MYSQL_USER: tarobee
      MYSQL_ROOT_PASSWORD: shohei17
      MYSQL_DATABASE: tarobee_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  # オブジェクトストレージ
  minio:
    image: quay.io/minio/minio
    container_name: common-minio
    networks:
      - common-net
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: shohei17
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: common-redis
    networks:
      - common-net
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always

networks:
  common-net:
    external: true
